### PR TITLE
Fix for WV-1716

### PR DESCRIPTION
**Pull request by SneakSnackSnake**
WV-1716 needs the ACKNOWLEDGE unicode character as a response, otherwise it keeps sending the same code.

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
did you test this in HA before making this PR?

**Comment by SneakSnackSnake** [comment]
I'm in the process of setting up the dev environment, so I haven't tested it yet in HA. My intention was to up the version so you can make a new release in PyPi. After that I was planning to test it in HA. 
I'm new to this, so I don't know if this is the correct way to do things. If not, I'm happy to accept your guidance.

**Comment by jeroenterheerdt** [comment]
You are right, I will update the pypi and let you know.

**Comment by jeroenterheerdt** [comment]
Just uploaded the package to pypi: https://pypi.org/project/pythonegardia/1.0.40/. Please go ahead and test it in your HA install.

**Comment by SneakSnackSnake** [comment]
Thanks, I appreciate it.

**Pull request merged**
